### ISSUE TITLE
Failed to activate the mcduino package

### ISSUE THREAD

**Issue by adamsloma** [marcelocorreia/mcduino#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.2
**Thrown From**: [mcduino](https://github.com/marcelocorreia/mcduino) package, v0.15.0
### Stack Trace

Failed to activate the mcduino package

```
At ENOENT: no such file or directory, open 'undefined/Contents/Resources/Java//hardware/arduino/boards.txt'

Error: ENOENT: no such file or directory, open 'undefined/Contents/Resources/Java//hardware/arduino/boards.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at Function.module.exports.Utils.getModelsList (/Users/adamsloma/.atom/packages/mcduino/lib/utils.coffee:55:20)
    at Object.<anonymous> (/Users/adamsloma/.atom/packages/mcduino/lib/main.coffee:35:23)
    at Object.<anonymous> (/Users/adamsloma/.atom/packages/mcduino/lib/main.coffee:345:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
```
### Commands

```
     -0:25.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:19.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:19 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:18.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:17.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:17.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:16.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:10.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:07.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.7.0 mcduino:ino-upload (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.5.4
autocomplete-python, v0.5.1
autocomplete-ruby, v0.1.0
mcduino, v0.15.0
seti-syntax, v0.4.0

# Dev
No dev packages
```

**Comment by mcpanthacorp** [comment]
Hi Adam,
Please update your package and set the Arduino path in the settings page.
Let me know if you are still unable to run it.
Cheers

**Comment by marcelocorreia** [comment]
Hi Adam,
Please update your package and set the Arduino path in the settings page.
Let me know if you are still unable to run it.
Cheers

**Comment by adamsloma** [comment]
What do I set the Arduino path to?

**Comment by adamsloma** [comment]
Also I'm in the settings page and there's nowhere to update any path....
![screen shot 2015-07-28 at 9 41 20 am](https://cloud.githubusercontent.com/assets/7192021/8937371/d37b8f8a-350c-11e5-8e90-d1c56e512a8d.png)

**Comment by mcpanthacorp** [comment]
Hi Adam,

Sorry for the late response, I have found bug when starting the package without the arduino path set.
It's fixed now and should start fine.
Sorry for the inconvenience

Thanks

**Comment by mcpanthacorp** [comment]
And,

You should find the Settings sections available when you got to Preferences -> Packages -> mcduino.
in case you want to play around with the settings

Cheers
